version: '3'

networks:
  web:
    name: web
    external: true
  backend:
    name: backend
    external: true


services:
  paragon-angular-universal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./dist/paragonProduction:/app/