version: '3'

networks:
  web:
    name: web
    external: true
  backend:
    name: backend
    external: true


services:
  paragon-angular-universal:
    container_name: paragon-angular-universal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./dist/paragon-angular:/app/
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.paragon.rule=Host(`staging.wearenv.co.uk`) && Path(`/paragon-angular`)"
    #   - "traefik.http.routers.paragon.entrypoints=web"
    #   - "traefik.http.services.paragon.loadbalancer.server.port=4000"
    networks:
      - web
      - backend
