[api]
	insecure = true

[entryPoints]
	[entryPoints.web]
		address = ":80"

[providers]
	[providers.docker]
		watch = true
		exposedByDefault = false
		network = "traefik-proxy"

[log]
	filePath = "/opt/traefik/error.log"
	format = 'json'
	level = "DEBUG"


[accessLog]
	filePath = "/opt/traefik/logs/access.log"
	format = "json"
	bufferingSize = 100


